### ISSUE TITLE
No test case for 'extended' length objects

### ISSUE THREAD

**Issue by dneise** [fact-project/pyeventio#17]
I think I made a mistake in how I treated this 'extended' length stuff, where `length` can be 42bit instead of 30bit. This only happens if objects are very large, or subtrees are very large. 
Very large means larger than 1GiB. 

The fact this error was not discovered is ob course, because we don't have a test case for this.
Delivering a test file larger than 1GiB is out of the question. But a zipped testfile, with a hypothetical very large object full of zeros, might be possible, since this can be zipped very efficiently. 

Such a file we don't have, and creating it falls into the realm of implementing an eventio writer.

Having a writer for our reader is very good, since it makes testing more complete...

**Comment by dneise** [comment]
c.f. 0f9bdc1e807a01415ce8af93045727a06396965e

**Comment by dneise** [comment]
Okay, now after banning magic numbers from the code base and re-reading the relevant part in "eventio_en.pdf" I can confirm there was an unknown bug before, which is now fixed. 
This by banning magic numbers and using 2 simple functions and 4 lines of extra comments I think it should be clear what is going on.

Still ... a test would be great.

**Comment by MaxNoe** [comment]
Even larger Prod3b and Prod4 files do not contain any of these extended length objects.
So I'm closing for now.

It someone has a file with extended length objects, please open a new issue.

**Comment by maxnoe** [comment]
I am writing this way too late, but here we go. 

Turns out (three month after I closed this issue) I ran into a bug in eventio itself, which seems to have been there forever.  
A cast was not properly done resulting in the wrong length being written into the extended field, which would prevent reading any extended length object, since all files with extended length objects have the wrong length in their header.

Before:
```
size_t len2 = (uint32_t) (((size_t)value) & ~0x3FFFFFFFUL) >> 30;
```
After:
```
size_t len2 = (uint32_t) ((((size_t)value) & ~0x3FFFFFFFUL) >> 30);
```

I only ran into this issue because I was trying to produce images of the whole Cherenkov footprint of high energy showers including the emitter information, the 10 TeV Iron event I simulated resulted in  6GiB large file, triggering the creation of an extended length photon block and thus the bug.

After trying to debug pyeventio for far too long, I found the code here to be correct and then the code in eventio.c to be the actual source of the problems.

Here is the image:
![iron_footprint](https://user-images.githubusercontent.com/5488440/214883033-502c94f2-8e59-44f1-bff0-e708023a96e7.png)
