### ISSUE TITLE
Direction cosine

### ISSUE THREAD

**Issue by dvanelten** [fact-project/pyeventio#24]
In the ReadMe, it says:

> direction cosine cx, cy in x and y direction of the incident angle of the photon

Is the meaning of cx, cy = u,v?

**Comment by MaxNoe** [comment]
From the corsika manual, Table 11:

> u direction cosine97 to x-axis
> v direction cosine97 to y-axis

https://web.ikp.kit.edu/corsika/usersguide/usersguide.pdf

**Comment by MaxNoe** [comment]
Maybe we should rename this to folow the corsika notation

**Comment by dneise** [comment]
To cite uncle bob again: http://www.itiseezee.com/?p=83

1.) Avoid mental mapping: so yes one should follow existing notations. 

2.) Choose good variable names: So no, one should change the notation in Corsika from the unintuitive single letter name "u" to something longer and easier  to understand, "cx" is also not good. 

He also says somewhere (cannot find the page at the moment), that one should not workaround broken software, but fix it. In this sense we talk about fixing corsika, just a tiny little bit by renaming "u" into "dir_cos_x" or so .. any name is better than "u" ... apart from "i" maybe.

----

For this project one could also think about this:
The user (a physicist I presume) is interested in information about particles, like `position, `momentum`, `energy` or `mass` or whatever. So instead of outputting `x` and `y`, and let the user deduce `z`, which is implicitly given by something called "observation plane", we could output something called `position`. We still have to explain in which coordinate system we give the position and which units we use, but at least we give a full position. Similar things come to mind, when we think about the momentum, which is given by these direction cosines... 

What do you think? should this software help the user to go one layer of abstraction up or not?

**Comment by MaxNoe** [comment]
I'd say we should keep it simple here.
