### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by MaxNoe** [fact-project/pyeventio#4]
Looks very similar...

**Comment by dneise** [comment]
I think one is trying to read the entire file, so one has random access to events and headers and can jump back and forth and look at stuff. The other tries to yield events when iterating over it ...
I didn't look at the code, I just remember I wanted to do something like that, since there were different users wanting different things bach at the time.

The whole code is a mess and shows that I had no idea where I was going.
@mackaiver told me he had 2 students who would like to learn something about coding and stuff. I would recommend anybody to consider a complete rewrite. However, I before I would like to define the API, maybe using functional tests. So the students can try some TDD concepts if they like.

**Comment by MaxNoe** [comment]
Yes, but I think we should give the two students a working bases to build upon. This is why I started to look into this.

**Comment by dneise** [comment]
Also possible .. but let's talk a little bit about the feature we want the end product to have and document them in functional test, so this "working base" is not only doing what you think is best.

**Comment by MaxNoe** [comment]
My goal would be something that can understand every valid EventIO File, as in see how many Objects are in there and of what types.

 I thought of an API similiar to `astropy.fits` where the top level fits object is basically a list of HDUs. Which is I think kind of native for a container file format like EventIO.
I could think of a `__repr__` like this:
```
EventIOFile(
    EventIOObject(type_id=1200, type='corsika_run_header'),
    EventIOObject(type_id=1598, type='unknown'),
)
```

Right now, this reader assumes a fixed structure of Objects as written by the IACT extension.

We should gradually add support for more Objects, starting with IACT output and after that sim_telarray output.

**Comment by dneise** [comment]
I think this is what `eventio.file.object_tree` does now in #14. So this can be closed as soon as that is merged.
